### ISSUE TITLE
AssertionError: Data augmentation for geometric consistency about inversion is not suitable for forward action

### ISSUE THREAD

**Issue by AshwiniUthir** [Xiaoming-Zhao/PointNav-VO#9]
I am following the instructions from TRAIN.md to train VO model. I am done with the data generation step. I haven't made any changes to the code and I am only trying to recreate the checkpoint for VO. I am getting the following error while running the command `python ${POINTNAV_VO_ROOT}/launch.py --repo-path ${POINTNAV_VO_ROOT} --n_gpus 1 --task-type vo --noise 1 --run-type train --addr 127.0.1.1 --port 8338` :
AssertionError: Data augmentation for geometric consistency about inversion is not suitable for forward action

Am I missing something here? Can someone please help me resolve this ?

**Comment by Xiaoming-Zhao** [comment]
If you want to train VO for "forward" action, you cannot set `invariance_types`
https://github.com/Xiaoming-Zhao/PointNav-VO/blob/ec208134369b0ebb7ced66b25290dcd6f02eab81/configs/vo/vo_pointnav.yaml#L91

The assertion error is here:
https://github.com/Xiaoming-Zhao/PointNav-VO/blob/49bbcfe4d4d54b85e740050d34310cf125a85d46/pointnav_vo/vo/dataset/regression_geo_invariance_iter_dataset.py#L83

The reason is that there is not action for `move_backward` so we should not use augmentation for `move_forward`.
